export enum ClientRoutes {
  HOME = "/",
  LOGIN = "/login",
  LOGOUT = "/logout",
  REGISTER = "/register",
  PROFILE = "/profile",
  CHECKOUT = "/checkout",
  RESTAURANTS = "/restaurants/:location",
  RESTAURANT_MENU = "/restaurantMenu/:titulo",
  RESTAURANT_CREATE = "/restaurantCreate/",
  RESTAURANT_MODIFIED = "/restaurantModified",
  RESTAURANT_DELETE = "/restaurantDelete",
  PRODUCT_CREATE = "/productCreate/",
  HOME_COMERCIANTE = "/comerciante",
  HOME_REPARTIDOR = "/repartidor",
  ORDERS_LIST = "/restaurants/orders/pendings",
  ORDERS_LIST_DISTRIBUTOR = "/repartidor/orders/pendings",
}
